### ISSUE TITLE
What is the current state of this project?

### ISSUE THREAD

**Issue by claudemirogb** [trustmaster/goflow#33]
I see that it has many issues that remains open. The last commit was last year. @trustmaster do you have any specific plan for this project?

Thank you

**Comment by trustmaster** [comment]
This project has been suspended while I've been busy in https://github.com/noflo/noflo lands.

I want to continue work on it but there's no specific time span. Here is my current roadmap for this project:

1. Drop reactive components support and stick with [active components](https://github.com/trustmaster/goflow/blob/master/component_test.go#L400) only. In reality active components proved to be way more practical and it would also simplify the runtime.
2. Complete NoFlo-UI/Flowhub integration.
3. Use it in real applications and implement whatever comes reasonable while doing so.

**Comment by Chillance** [comment]
Any updates here? Seems like the websocket over at golang.org/x/net/websocket isn't available anymore.

**Comment by trustmaster** [comment]
@Chillance I was able to `go get golang.org/x/net/websocket` today without a problem. Could it be a network problem?

However, package tests are not passing with recent Go versions. I'll have a look at it.

**Comment by Chillance** [comment]
Possibly a network problem, although it seemed to me that it wasn't there anymore. Especially since they also say this:

"This package currently lacks some features found in an alternative and more actively maintained WebSocket package:

https://godoc.org/github.com/gorilla/websocket"

So, could you possibly change to use gorilla instead? I will try again and see if it works in the meantime.

**Comment by Chillance** [comment]
Ok, so a go get of this worked now it seems. Could still be an idea to change to gorillas websocket.

**Comment by trustmaster** [comment]
See #35

**Comment by Chillance** [comment]
Cool! Thanks!
